In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['MedHouseValue'] = pd.Series(housing.target)

target = df['MedHouseValue']
features = df.drop('MedHouseValue', axis=1)
df.tail()

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.1, random_state=0)

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print(X_test)

model = LinearRegression()
model.fit(X_train, y_train)

print("Intercept: ", model.intercept_)
print("Slope (Coefficients): ", model.coef_)

rmse_train = np.sqrt(mean_squared_error(y_train, model.predict(X_train)))
rmse_test = np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

r2_train = model.score(X_train, y_train)
r2_test = model.score(X_test, y_test)

print("RMSE Train: ", rmse_train)
print("RMSE Test: ", rmse_test)
print("R^2 Train:", r2_train)
print("R^2 Test: ", r2_test)

[[0.2518517  0.41176471 0.0341473  ... 0.0058233  0.0042508  0.72709163]
 [0.36411222 0.60784314 0.03729592 ... 0.00388746 0.1466525  0.63545817]
 [0.26543082 0.54901961 0.0360446  ... 0.00370238 0.64930925 0.25      ]
 ...
 [0.29236838 0.43137255 0.02916552 ... 0.00414475 0.1381509  0.60358566]
 [0.25790679 0.92156863 0.03391022 ... 0.00291045 0.17321998 0.59960159]
 [0.1255431  0.39215686 0.02547297 ... 0.00279535 0.03081828 0.73904382]]
Intercept:  3.7262879929739228
Slope (Coefficients):  [  6.30337643   0.48015061 -14.58191203  21.01421395  -0.19420135
  -3.17143717  -3.94818441  -4.34265315]
RMSE Train:  0.72339468552174
RMSE Test:  0.7322922782112146
R^2 Train: 0.6055884194496246
R^2 Test:  0.6098033978087847
